# Generated by Django 5.2.3 on 2025-07-28 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lesson_author_userprofile_avatar_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['id'], 'verbose_name': 'Progresses', 'verbose_name_plural': 'Progress'},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='last_activity',
        ),
        migrations.CreateModel(
            name='LessonViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_log', to='main.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_log', to='main.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_view_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_view_log',
                'indexes': [models.Index(fields=['-last_activity'], name='lesson_view_last_ac_bddbae_idx')],
            },
        ),
    ]
