# Generated by Django 5.2.3 on 2025-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_progress_options_remove_progress_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonviewlog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
