# Generated by Django 5.2.3 on 2025-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lessonviewlog_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='started',
            field=models.ManyToManyField(blank=True, related_name='started_by', to='main.course'),
        ),
    ]
