# Generated by Django 5.2.3 on 2025-08-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='finished',
            field=models.ManyToManyField(blank=True, related_name='finished_by', to='main.course'),
        ),
    ]
