# Generated by Django 5.2.3 on 2025-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userprofile_favorites_course_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='main.course'),
        ),
    ]
