# Generated by Django 5.2.3 on 2025-07-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_course_favorites_userprofile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], null=True),
        ),
    ]
