# Generated by Django 5.2.3 on 2025-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='main.course'),
        ),
    ]
